apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ljakimczuk-temporary-repository
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/ljakimczuk/temporary-repository
